name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Authenticate with Firebase CLI
        run: |
          echo ${{ secrets.FIREBASE_TOKEN }}

      - name: Build and Deploy with Fastlane
        run: bundle exec fastlane deploy
